### ISSUE TITLE
Incorrect calculation of swarm hash

### ISSUE THREAD

**Issue by AnonymousMonkey2021** [eth-sri/ilf#11]
https://github.com/eth-sri/ilf/blob/9d2ae9b2360d9533ed30e3b59ebd212ab085cc30/execution/contract.go#L16
https://github.com/eth-sri/ilf/blob/9d2ae9b2360d9533ed30e3b59ebd212ab085cc30/execution/contract.go#L89

https://docs.soliditylang.org/en/v0.5.3/metadata.html#encoding-of-the-metadata-hash-in-the-bytecode

According to the solidity doc, the swarm hash is padded like this `0xa1 0x65 'b' 'z' 'z' 'r' '0' 0x58 0x20 <32 bytes swarm hash> 0x00 0x29`. 

This would mean that your swarm hash is 2 bytes off.

**Comment by LostBenjamin** [comment]
Fixed in [this commit](https://github.com/eth-sri/ilf/commit/d855cda12e6f1ff36936ed98dae95326bc4f3154). Thanks for reporting the issue.
