### ISSUE TITLE
Problem with docker build

### ISSUE THREAD

**Issue by AnonymousMonkey2021** [eth-sri/ilf#12]
As of today, during the pip install phase of docker build, it failed due to a package called coincurve, which is installed with the ethereum package. The problem is the newer version of coincurve. Simply add `coincurve==12.0.0` before `ethereum `in the `requirements.txt` file will fix the problem.

**Comment by LostBenjamin** [comment]
Fixed in [this commit](https://github.com/eth-sri/ilf/commit/d855cda12e6f1ff36936ed98dae95326bc4f3154). Thanks for reporting the issue.
