### ISSUE TITLE
How to train the ifl_w2v.pkl?

### ISSUE THREAD

**Issue by harperchen** [eth-sri/ilf#13]
May I know how do you get the ifl_w2v.pkl? Do you directly use word2vec model on the training data?

**Comment by LostBenjamin** [comment]
Hi,

We just obtained the vocabulary of function names (significantly smaller than the vocabulary of word2vec) in our dataset and then extracted the word embeddings of the function names from word2vec.

Best,
Jingxuan

**Comment by harperchen** [comment]
Thanks for the answer!
