### ISSUE TITLE
Training set and benchmark dataset

### ISSUE THREAD

**Issue by ailen-wrx** [eth-sri/ilf#16]
Hi, I'm wondering if you have released the training set that can reproduce the pretrained model, as well as the benchmark dataset you used for evaluation in the paper?

**Comment by LostBenjamin** [comment]
Hi Ruixin,

We haven't released those dataset yet. We will let you know if we plan to release them.

Best,
Jingxuan

**Comment by ailen-wrx** [comment]
Thanks for the follow-up! 

Best,
ailen
